/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "id.sifa.defs";

export { $nsid };

/** The type of employment arrangement. */
type EmploymentType =
  | "id.sifa.defs#fullTime"
  | "id.sifa.defs#partTime"
  | "id.sifa.defs#contract"
  | "id.sifa.defs#freelance"
  | "id.sifa.defs#internship"
  | "id.sifa.defs#apprenticeship"
  | "id.sifa.defs#volunteer"
  | "id.sifa.defs#selfEmployed"
  | l.UnknownString;

export type { EmploymentType };

/** The type of employment arrangement. */
const employmentType = l.string<{
  knownValues: [
    "id.sifa.defs#fullTime",
    "id.sifa.defs#partTime",
    "id.sifa.defs#contract",
    "id.sifa.defs#freelance",
    "id.sifa.defs#internship",
    "id.sifa.defs#apprenticeship",
    "id.sifa.defs#volunteer",
    "id.sifa.defs#selfEmployed",
  ];
}>();

export { employmentType };

/** Full-time employment. */
type FullTime = "id.sifa.defs#fullTime";

export type { FullTime };

/** Full-time employment. */
const fullTime = l.token($nsid, "fullTime");

export { fullTime };

/** Part-time employment. */
type PartTime = "id.sifa.defs#partTime";

export type { PartTime };

/** Part-time employment. */
const partTime = l.token($nsid, "partTime");

export { partTime };

/** Contract/temporary employment. */
type Contract = "id.sifa.defs#contract";

export type { Contract };

/** Contract/temporary employment. */
const contract = l.token($nsid, "contract");

export { contract };

/** Freelance/independent work. */
type Freelance = "id.sifa.defs#freelance";

export type { Freelance };

/** Freelance/independent work. */
const freelance = l.token($nsid, "freelance");

export { freelance };

/** Internship position. */
type Internship = "id.sifa.defs#internship";

export type { Internship };

/** Internship position. */
const internship = l.token($nsid, "internship");

export { internship };

/** Apprenticeship position. */
type Apprenticeship = "id.sifa.defs#apprenticeship";

export type { Apprenticeship };

/** Apprenticeship position. */
const apprenticeship = l.token($nsid, "apprenticeship");

export { apprenticeship };

/** Volunteer work (when used as employment type). */
type Volunteer = "id.sifa.defs#volunteer";

export type { Volunteer };

/** Volunteer work (when used as employment type). */
const volunteer = l.token($nsid, "volunteer");

export { volunteer };

/** Self-employed. */
type SelfEmployed = "id.sifa.defs#selfEmployed";

export type { SelfEmployed };

/** Self-employed. */
const selfEmployed = l.token($nsid, "selfEmployed");

export { selfEmployed };

/** The workplace arrangement. */
type WorkplaceType =
  | "id.sifa.defs#onSite"
  | "id.sifa.defs#remote"
  | "id.sifa.defs#hybrid"
  | l.UnknownString;

export type { WorkplaceType };

/** The workplace arrangement. */
const workplaceType = l.string<{
  knownValues: [
    "id.sifa.defs#onSite",
    "id.sifa.defs#remote",
    "id.sifa.defs#hybrid",
  ];
}>();

export { workplaceType };

/** On-site/in-office work. */
type OnSite = "id.sifa.defs#onSite";

export type { OnSite };

/** On-site/in-office work. */
const onSite = l.token($nsid, "onSite");

export { onSite };

/** Fully remote work. */
type Remote = "id.sifa.defs#remote";

export type { Remote };

/** Fully remote work. */
const remote = l.token($nsid, "remote");

export { remote };

/** Hybrid on-site and remote work. */
type Hybrid = "id.sifa.defs#hybrid";

export type { Hybrid };

/** Hybrid on-site and remote work. */
const hybrid = l.token($nsid, "hybrid");

export { hybrid };

/** Language proficiency level. Maps to LinkedIn's five-level scale for lossless import. */
type Proficiency =
  | "id.sifa.defs#elementary"
  | "id.sifa.defs#limitedWorking"
  | "id.sifa.defs#professionalWorking"
  | "id.sifa.defs#fullProfessional"
  | "id.sifa.defs#native"
  | l.UnknownString;

export type { Proficiency };

/** Language proficiency level. Maps to LinkedIn's five-level scale for lossless import. */
const proficiency = l.string<{
  knownValues: [
    "id.sifa.defs#elementary",
    "id.sifa.defs#limitedWorking",
    "id.sifa.defs#professionalWorking",
    "id.sifa.defs#fullProfessional",
    "id.sifa.defs#native",
  ];
}>();

export { proficiency };

/** Elementary proficiency. */
type Elementary = "id.sifa.defs#elementary";

export type { Elementary };

/** Elementary proficiency. */
const elementary = l.token($nsid, "elementary");

export { elementary };

/** Limited working proficiency. */
type LimitedWorking = "id.sifa.defs#limitedWorking";

export type { LimitedWorking };

/** Limited working proficiency. */
const limitedWorking = l.token($nsid, "limitedWorking");

export { limitedWorking };

/** Professional working proficiency. */
type ProfessionalWorking = "id.sifa.defs#professionalWorking";

export type { ProfessionalWorking };

/** Professional working proficiency. */
const professionalWorking = l.token($nsid, "professionalWorking");

export { professionalWorking };

/** Full professional proficiency. */
type FullProfessional = "id.sifa.defs#fullProfessional";

export type { FullProfessional };

/** Full professional proficiency. */
const fullProfessional = l.token($nsid, "fullProfessional");

export { fullProfessional };

/** Native or bilingual proficiency. */
type Native$0 = "id.sifa.defs#native";

export type { Native$0 as Native };

/** Native or bilingual proficiency. */
const native$0 = l.token($nsid, "native");

export { native$0 as "native" };

/** Broad category for grouping skills. */
type SkillCategory =
  | "id.sifa.defs#technical"
  | "id.sifa.defs#business"
  | "id.sifa.defs#creative"
  | "id.sifa.defs#interpersonal"
  | "id.sifa.defs#language"
  | "id.sifa.defs#industry"
  | l.UnknownString;

export type { SkillCategory };

/** Broad category for grouping skills. */
const skillCategory = l.string<{
  knownValues: [
    "id.sifa.defs#technical",
    "id.sifa.defs#business",
    "id.sifa.defs#creative",
    "id.sifa.defs#interpersonal",
    "id.sifa.defs#language",
    "id.sifa.defs#industry",
  ];
}>();

export { skillCategory };

/** Technical/engineering skills. */
type Technical = "id.sifa.defs#technical";

export type { Technical };

/** Technical/engineering skills. */
const technical = l.token($nsid, "technical");

export { technical };

/** Business and management skills. */
type Business = "id.sifa.defs#business";

export type { Business };

/** Business and management skills. */
const business = l.token($nsid, "business");

export { business };

/** Creative and design skills. */
type Creative = "id.sifa.defs#creative";

export type { Creative };

/** Creative and design skills. */
const creative = l.token($nsid, "creative");

export { creative };

/** Interpersonal and communication skills. */
type Interpersonal = "id.sifa.defs#interpersonal";

export type { Interpersonal };

/** Interpersonal and communication skills. */
const interpersonal = l.token($nsid, "interpersonal");

export { interpersonal };

/** Language and linguistic skills. */
type Language = "id.sifa.defs#language";

export type { Language };

/** Language and linguistic skills. */
const language = l.token($nsid, "language");

export { language };

/** Industry-specific domain knowledge. */
type Industry = "id.sifa.defs#industry";

export type { Industry };

/** Industry-specific domain knowledge. */
const industry = l.token($nsid, "industry");

export { industry };

/** The type of opportunity the user is open to. */
type OpenToWorkStatus =
  | "id.sifa.defs#fullTimeRoles"
  | "id.sifa.defs#partTimeRoles"
  | "id.sifa.defs#contractRoles"
  | "id.sifa.defs#boardPositions"
  | "id.sifa.defs#mentoringOthers"
  | "id.sifa.defs#beingMentored"
  | "id.sifa.defs#collaborations"
  | l.UnknownString;

export type { OpenToWorkStatus };

/** The type of opportunity the user is open to. */
const openToWorkStatus = l.string<{
  knownValues: [
    "id.sifa.defs#fullTimeRoles",
    "id.sifa.defs#partTimeRoles",
    "id.sifa.defs#contractRoles",
    "id.sifa.defs#boardPositions",
    "id.sifa.defs#mentoringOthers",
    "id.sifa.defs#beingMentored",
    "id.sifa.defs#collaborations",
  ];
}>();

export { openToWorkStatus };

/** Open to full-time employment opportunities. */
type FullTimeRoles = "id.sifa.defs#fullTimeRoles";

export type { FullTimeRoles };

/** Open to full-time employment opportunities. */
const fullTimeRoles = l.token($nsid, "fullTimeRoles");

export { fullTimeRoles };

/** Open to part-time employment opportunities. */
type PartTimeRoles = "id.sifa.defs#partTimeRoles";

export type { PartTimeRoles };

/** Open to part-time employment opportunities. */
const partTimeRoles = l.token($nsid, "partTimeRoles");

export { partTimeRoles };

/** Open to contract or freelance work. */
type ContractRoles = "id.sifa.defs#contractRoles";

export type { ContractRoles };

/** Open to contract or freelance work. */
const contractRoles = l.token($nsid, "contractRoles");

export { contractRoles };

/** Open to advisory or board positions. */
type BoardPositions = "id.sifa.defs#boardPositions";

export type { BoardPositions };

/** Open to advisory or board positions. */
const boardPositions = l.token($nsid, "boardPositions");

export { boardPositions };

/** Open to mentoring others. */
type MentoringOthers = "id.sifa.defs#mentoringOthers";

export type { MentoringOthers };

/** Open to mentoring others. */
const mentoringOthers = l.token($nsid, "mentoringOthers");

export { mentoringOthers };

/** Open to being mentored. */
type BeingMentored = "id.sifa.defs#beingMentored";

export type { BeingMentored };

/** Open to being mentored. */
const beingMentored = l.token($nsid, "beingMentored");

export { beingMentored };

/** Open to project collaborations. */
type Collaborations = "id.sifa.defs#collaborations";

export type { Collaborations };

/** Open to project collaborations. */
const collaborations = l.token($nsid, "collaborations");

export { collaborations };

/** Platform type for an external account linked to a Sifa profile. */
type ExternalPlatform =
  | "id.sifa.defs#platformRss"
  | "id.sifa.defs#platformFediverse"
  | "id.sifa.defs#platformTwitter"
  | "id.sifa.defs#platformInstagram"
  | "id.sifa.defs#platformGithub"
  | "id.sifa.defs#platformYoutube"
  | "id.sifa.defs#platformLinkedin"
  | "id.sifa.defs#platformSubstack"
  | "id.sifa.defs#platformWebsite"
  | "id.sifa.defs#platformOrcid"
  | "id.sifa.defs#platformOther"
  | l.UnknownString;

export type { ExternalPlatform };

/** Platform type for an external account linked to a Sifa profile. */
const externalPlatform = l.string<{
  knownValues: [
    "id.sifa.defs#platformRss",
    "id.sifa.defs#platformFediverse",
    "id.sifa.defs#platformTwitter",
    "id.sifa.defs#platformInstagram",
    "id.sifa.defs#platformGithub",
    "id.sifa.defs#platformYoutube",
    "id.sifa.defs#platformLinkedin",
    "id.sifa.defs#platformSubstack",
    "id.sifa.defs#platformWebsite",
    "id.sifa.defs#platformOrcid",
    "id.sifa.defs#platformOther",
  ];
}>();

export { externalPlatform };

/** RSS or Atom feed (blog, newsletter, podcast). */
type PlatformRss = "id.sifa.defs#platformRss";

export type { PlatformRss };

/** RSS or Atom feed (blog, newsletter, podcast). */
const platformRss = l.token($nsid, "platformRss");

export { platformRss };

/** Fediverse account (Mastodon, Misskey, Pleroma, etc.). */
type PlatformFediverse = "id.sifa.defs#platformFediverse";

export type { PlatformFediverse };

/** Fediverse account (Mastodon, Misskey, Pleroma, etc.). */
const platformFediverse = l.token($nsid, "platformFediverse");

export { platformFediverse };

/** Twitter/X account. */
type PlatformTwitter = "id.sifa.defs#platformTwitter";

export type { PlatformTwitter };

/** Twitter/X account. */
const platformTwitter = l.token($nsid, "platformTwitter");

export { platformTwitter };

/** Instagram account. */
type PlatformInstagram = "id.sifa.defs#platformInstagram";

export type { PlatformInstagram };

/** Instagram account. */
const platformInstagram = l.token($nsid, "platformInstagram");

export { platformInstagram };

/** GitHub account. */
type PlatformGithub = "id.sifa.defs#platformGithub";

export type { PlatformGithub };

/** GitHub account. */
const platformGithub = l.token($nsid, "platformGithub");

export { platformGithub };

/** YouTube channel. */
type PlatformYoutube = "id.sifa.defs#platformYoutube";

export type { PlatformYoutube };

/** YouTube channel. */
const platformYoutube = l.token($nsid, "platformYoutube");

export { platformYoutube };

/** LinkedIn profile. */
type PlatformLinkedin = "id.sifa.defs#platformLinkedin";

export type { PlatformLinkedin };

/** LinkedIn profile. */
const platformLinkedin = l.token($nsid, "platformLinkedin");

export { platformLinkedin };

/** Substack newsletter. */
type PlatformSubstack = "id.sifa.defs#platformSubstack";

export type { PlatformSubstack };

/** Substack newsletter. */
const platformSubstack = l.token($nsid, "platformSubstack");

export { platformSubstack };

/** Personal or professional website. */
type PlatformWebsite = "id.sifa.defs#platformWebsite";

export type { PlatformWebsite };

/** Personal or professional website. */
const platformWebsite = l.token($nsid, "platformWebsite");

export { platformWebsite };

/** ORCID researcher identifier. */
type PlatformOrcid = "id.sifa.defs#platformOrcid";

export type { PlatformOrcid };

/** ORCID researcher identifier. */
const platformOrcid = l.token($nsid, "platformOrcid");

export { platformOrcid };

/** Other platform not covered by specific tokens. */
type PlatformOther = "id.sifa.defs#platformOther";

export type { PlatformOther };

/** Other platform not covered by specific tokens. */
const platformOther = l.token($nsid, "platformOther");

export { platformOther };

/** The role a location plays in a user's professional profile. */
type LocationType =
  | "id.sifa.defs#locationPrimary"
  | "id.sifa.defs#locationBusiness"
  | "id.sifa.defs#locationTravel"
  | l.UnknownString;

export type { LocationType };

/** The role a location plays in a user's professional profile. */
const locationType = l.string<{
  knownValues: [
    "id.sifa.defs#locationPrimary",
    "id.sifa.defs#locationBusiness",
    "id.sifa.defs#locationTravel",
  ];
}>();

export { locationType };

/** Primary residence or home location. */
type LocationPrimary = "id.sifa.defs#locationPrimary";

export type { LocationPrimary };

/** Primary residence or home location. */
const locationPrimary = l.token($nsid, "locationPrimary");

export { locationPrimary };

/** Business or operational location. */
type LocationBusiness = "id.sifa.defs#locationBusiness";

export type { LocationBusiness };

/** Business or operational location. */
const locationBusiness = l.token($nsid, "locationBusiness");

export { locationBusiness };

/** Frequent travel or temporary location. */
type LocationTravel = "id.sifa.defs#locationTravel";

export type { LocationTravel };

/** Frequent travel or temporary location. */
const locationTravel = l.token($nsid, "locationTravel");

export { locationTravel };

/** A structured location address. countryCode is the single source of truth for the country; AppViews resolve it to a display name. */
type LocationAddress = {
  $type?: "id.sifa.defs#locationAddress";

  /**
   * ISO 3166-1 alpha-2 country code (e.g. 'NL', 'US').
   */
  countryCode: string;

  /**
   * Administrative region (state, province, etc.). Free text — AppViews display as-is.
   */
  region?: string;

  /**
   * City or locality name. Free text.
   */
  city?: string;
};

export type { LocationAddress };

/** A structured location address. countryCode is the single source of truth for the country; AppViews resolve it to a display name. */
const locationAddress = l.typedObject<LocationAddress>(
  $nsid,
  "locationAddress",
  l.object({
    countryCode: l.string({ minLength: 2, maxLength: 2 }),
    region: l.optional(l.string({ maxGraphemes: 100, maxLength: 1000 })),
    city: l.optional(l.string({ maxGraphemes: 100, maxLength: 1000 })),
  }),
);

export { locationAddress };

/** A reference to an id.sifa.profile.skill record by AT-URI. No CID is required because skills are mutable records in the same user's repo. */
type SkillRef = {
  $type?: "id.sifa.defs#skillRef";

  /**
   * AT-URI of the id.sifa.profile.skill record.
   */
  uri: l.AtUriString;
};

export type { SkillRef };

/** A reference to an id.sifa.profile.skill record by AT-URI. No CID is required because skills are mutable records in the same user's repo. */
const skillRef = l.typedObject<SkillRef>(
  $nsid,
  "skillRef",
  l.object({ uri: l.string({ format: "at-uri" }) }),
);

export { skillRef };

/** Role within a collaborative project. */
type ProjectRole =
  | "id.sifa.defs#projectOwner"
  | "id.sifa.defs#projectCore"
  | "id.sifa.defs#projectContributor"
  | l.UnknownString;

export type { ProjectRole };

/** Role within a collaborative project. */
const projectRole = l.string<{
  knownValues: [
    "id.sifa.defs#projectOwner",
    "id.sifa.defs#projectCore",
    "id.sifa.defs#projectContributor",
  ];
}>();

export { projectRole };

/** Project owner with full management permissions. Multiple owners are supported. */
type ProjectOwner = "id.sifa.defs#projectOwner";

export type { ProjectOwner };

/** Project owner with full management permissions. Multiple owners are supported. */
const projectOwner = l.token($nsid, "projectOwner");

export { projectOwner };

/** Core team member with elevated involvement. */
type ProjectCore = "id.sifa.defs#projectCore";

export type { ProjectCore };

/** Core team member with elevated involvement. */
const projectCore = l.token($nsid, "projectCore");

export { projectCore };

/** Project contributor. */
type ProjectContributor = "id.sifa.defs#projectContributor";

export type { ProjectContributor };

/** Project contributor. */
const projectContributor = l.token($nsid, "projectContributor");

export { projectContributor };

/** Current status of a collaborative project. */
type ProjectStatus =
  | "id.sifa.defs#projectActive"
  | "id.sifa.defs#projectCompleted"
  | "id.sifa.defs#projectArchived"
  | l.UnknownString;

export type { ProjectStatus };

/** Current status of a collaborative project. */
const projectStatus = l.string<{
  knownValues: [
    "id.sifa.defs#projectActive",
    "id.sifa.defs#projectCompleted",
    "id.sifa.defs#projectArchived",
  ];
}>();

export { projectStatus };

/** Project is actively maintained or in development. */
type ProjectActive = "id.sifa.defs#projectActive";

export type { ProjectActive };

/** Project is actively maintained or in development. */
const projectActive = l.token($nsid, "projectActive");

export { projectActive };

/** Project has been completed. */
type ProjectCompleted = "id.sifa.defs#projectCompleted";

export type { ProjectCompleted };

/** Project has been completed. */
const projectCompleted = l.token($nsid, "projectCompleted");

export { projectCompleted };

/** Project is archived and no longer active. */
type ProjectArchived = "id.sifa.defs#projectArchived";

export type { ProjectArchived };

/** Project is archived and no longer active. */
const projectArchived = l.token($nsid, "projectArchived");

export { projectArchived };
