/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.weareonhire.profile";

export { $nsid };

/** A user's professional profile for the weareonhire platform. */
type Main = {
  $type: "com.weareonhire.profile";

  /**
   * User's full name, e.g., John Doe
   */
  name?: string;

  /**
   * Professional title, e.g., Senior full-stack engineer
   */
  title?: string;

  /**
   * ISO 3166-1 alpha-2 country code, e.g., US, NL, DE
   */
  countryCode?: string;

  /**
   * Professional introduction or summary
   */
  introduction?: string;
  createdAt: l.DatetimeString;
};

export type { Main };

/** A user's professional profile for the weareonhire platform. */
const main = l.record<"literal:self", Main>(
  "literal:self",
  $nsid,
  l.object({
    name: l.optional(l.string({ minLength: 1, maxLength: 100 })),
    title: l.optional(l.string({ minLength: 1, maxLength: 200 })),
    countryCode: l.optional(l.string({ minLength: 2, maxLength: 2 })),
    introduction: l.optional(l.string({ minLength: 1, maxLength: 5000 })),
    createdAt: l.string({ format: "datetime" }),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
