/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "com.weareonhire.recommendation";

export { $nsid };

/** A professional recommendation from one user to another. */
type Main = {
  $type: "com.weareonhire.recommendation";
  subject: l.DidString;

  /**
   * Free-form recommendation text.
   */
  reason: string;
  createdAt: l.DatetimeString;
};

export type { Main };

/** A professional recommendation from one user to another. */
const main = l.record<"literal:subject_did", Main>(
  "literal:subject_did",
  $nsid,
  l.object({
    subject: l.string({ format: "did" }),
    reason: l.string({ minLength: 200, maxLength: 3000 }),
    createdAt: l.string({ format: "datetime" }),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
