/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as SifaDefs from '../defs.defs.js'
import * as LabelDefs from '../../../com/atproto/label/defs.defs.js'

const $nsid = 'id.sifa.profile.education'

export { $nsid }

/** Record representing a single education credential. */
type Main = {
  $type: 'id.sifa.profile.education'

  /**
   * Name of the educational institution.
   */
  institution: string

  /**
   * DID of the institution's ATproto account, if one exists.
   */
  institutionDid?: l.DidString

  /**
   * Degree name (e.g., 'Bachelor of Science', 'Master of Arts').
   */
  degree?: string

  /**
   * Field of study or major.
   */
  fieldOfStudy?: string

  /**
   * Grade, GPA, or classification achieved.
   */
  grade?: string

  /**
   * Activities, societies, and extracurriculars.
   */
  activities?: string

  /**
   * Additional description or notes about the education.
   */
  description?: string

  /**
   * Institution location.
   */
  location?: SifaDefs.LocationAddress

  /**
   * Start date in YYYY-MM or YYYY-MM-DD format.
   */
  startedAt?: string

  /**
   * End date (graduation or expected graduation) in YYYY-MM or YYYY-MM-DD format. Omit if currently enrolled.
   */
  endedAt?: string

  /**
   * Self-label values for this education record.
   */
  labels?: l.$Typed<LabelDefs.SelfLabels> | l.Unknown$TypedObject

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Record representing a single education credential. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    institution: l.string({ minLength: 1, maxGraphemes: 256, maxLength: 2560 }),
    institutionDid: l.optional(l.string({ format: 'did' })),
    degree: l.optional(l.string({ maxGraphemes: 256, maxLength: 2560 })),
    fieldOfStudy: l.optional(l.string({ maxGraphemes: 256, maxLength: 2560 })),
    grade: l.optional(l.string({ maxGraphemes: 50, maxLength: 500 })),
    activities: l.optional(l.string({ maxGraphemes: 1000, maxLength: 10000 })),
    description: l.optional(l.string({ maxGraphemes: 5000, maxLength: 50000 })),
    location: l.optional(
      l.ref<SifaDefs.LocationAddress>((() => SifaDefs.locationAddress) as any),
    ),
    startedAt: l.optional(l.string()),
    endedAt: l.optional(l.string()),
    labels: l.optional(
      l.typedUnion(
        [l.typedRef<LabelDefs.SelfLabels>((() => LabelDefs.selfLabels) as any)],
        false,
      ),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
