/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "id.sifa.profile.externalAccount";

export { $nsid };

/** Record representing a single external account or website linked by the user. */
type Main = {
  $type: "id.sifa.profile.externalAccount";

  /**
   * The platform or type of external account.
   */
  platform:
    | "id.sifa.defs#platformRss"
    | "id.sifa.defs#platformFediverse"
    | "id.sifa.defs#platformTwitter"
    | "id.sifa.defs#platformInstagram"
    | "id.sifa.defs#platformGithub"
    | "id.sifa.defs#platformYoutube"
    | "id.sifa.defs#platformLinkedin"
    | "id.sifa.defs#platformWebsite"
    | "id.sifa.defs#platformOrcid"
    | "id.sifa.defs#platformOther"
    | l.UnknownString;

  /**
   * The profile or site URL. Displayed as a clickable link on the user's profile.
   */
  url: l.UriString;

  /**
   * Optional display name for this account (e.g., 'My Blog', 'Photography').
   */
  label?: string;

  /**
   * Optional RSS or Atom feed URL. Auto-discovered or manually provided. Used for content rendering in the ATmosphere Stream.
   */
  feedUrl?: l.UriString;

  /**
   * Whether this is the user's primary external link, displayed prominently on the profile card.
   */
  isPrimary?: boolean;

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString;
};

export type { Main };

/** Record representing a single external account or website linked by the user. */
const main = l.record<"tid", Main>(
  "tid",
  $nsid,
  l.object({
    platform: l.string<{
      knownValues: [
        "id.sifa.defs#platformRss",
        "id.sifa.defs#platformFediverse",
        "id.sifa.defs#platformTwitter",
        "id.sifa.defs#platformInstagram",
        "id.sifa.defs#platformGithub",
        "id.sifa.defs#platformYoutube",
        "id.sifa.defs#platformLinkedin",
        "id.sifa.defs#platformWebsite",
        "id.sifa.defs#platformOrcid",
        "id.sifa.defs#platformOther",
      ];
    }>(),
    url: l.string({ format: "uri" }),
    label: l.optional(l.string({ maxGraphemes: 64, maxLength: 640 })),
    feedUrl: l.optional(l.string({ format: "uri" })),
    isPrimary: l.optional(l.boolean()),
    createdAt: l.string({ format: "datetime" }),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
