/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as SifaDefs from '../defs.defs.js'
import * as LabelDefs from '../../../com/atproto/label/defs.defs.js'

const $nsid = 'id.sifa.profile.position'

export { $nsid }

/** Record representing a single work position or role. */
type Main = {
  $type: 'id.sifa.profile.position'

  /**
   * Company or organization name.
   */
  company: string

  /**
   * DID of the company's ATproto account, if one exists. Enables verified company linking.
   */
  companyDid?: l.DidString

  /**
   * Job title or role name.
   */
  title: string

  /**
   * Description of responsibilities, achievements, and duties.
   */
  description?: string

  /**
   * Type of employment (full-time, part-time, contract, etc.).
   */
  employmentType?:
    | 'id.sifa.defs#fullTime'
    | 'id.sifa.defs#partTime'
    | 'id.sifa.defs#contract'
    | 'id.sifa.defs#freelance'
    | 'id.sifa.defs#internship'
    | 'id.sifa.defs#apprenticeship'
    | 'id.sifa.defs#volunteer'
    | 'id.sifa.defs#selfEmployed'
    | l.UnknownString

  /**
   * Workplace arrangement (on-site, remote, hybrid).
   */
  workplaceType?:
    | 'id.sifa.defs#onSite'
    | 'id.sifa.defs#remote'
    | 'id.sifa.defs#hybrid'
    | l.UnknownString

  /**
   * Work location.
   */
  location?: SifaDefs.LocationAddress

  /**
   * Start date of the position in YYYY-MM or YYYY-MM-DD format.
   */
  startedAt: string

  /**
   * End date of the position in YYYY-MM or YYYY-MM-DD format. Omit if this is a current position.
   */
  endedAt?: string

  /**
   * Skills used in this position. Each entry is a URI reference to an id.sifa.profile.skill record owned by the same DID.
   */
  skills?: SifaDefs.SkillRef[]

  /**
   * Whether this is the user's primary current position, displayed on the identity card.
   */
  isPrimary?: boolean

  /**
   * Self-label values for this position record.
   */
  labels?: l.$Typed<LabelDefs.SelfLabels> | l.Unknown$TypedObject

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Record representing a single work position or role. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    company: l.string({ minLength: 1, maxGraphemes: 256, maxLength: 2560 }),
    companyDid: l.optional(l.string({ format: 'did' })),
    title: l.string({ minLength: 1, maxGraphemes: 256, maxLength: 2560 }),
    description: l.optional(l.string({ maxGraphemes: 5000, maxLength: 50000 })),
    employmentType: l.optional(
      l.string<{
        knownValues: [
          'id.sifa.defs#fullTime',
          'id.sifa.defs#partTime',
          'id.sifa.defs#contract',
          'id.sifa.defs#freelance',
          'id.sifa.defs#internship',
          'id.sifa.defs#apprenticeship',
          'id.sifa.defs#volunteer',
          'id.sifa.defs#selfEmployed',
        ]
      }>(),
    ),
    workplaceType: l.optional(
      l.string<{
        knownValues: [
          'id.sifa.defs#onSite',
          'id.sifa.defs#remote',
          'id.sifa.defs#hybrid',
        ]
      }>(),
    ),
    location: l.optional(
      l.ref<SifaDefs.LocationAddress>((() => SifaDefs.locationAddress) as any),
    ),
    startedAt: l.string(),
    endedAt: l.optional(l.string()),
    skills: l.optional(
      l.array(l.ref<SifaDefs.SkillRef>((() => SifaDefs.skillRef) as any), {
        maxLength: 50,
      }),
    ),
    isPrimary: l.optional(l.boolean()),
    labels: l.optional(
      l.typedUnion(
        [l.typedRef<LabelDefs.SelfLabels>((() => LabelDefs.selfLabels) as any)],
        false,
      ),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
