/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs.js'
import * as LabelDefs from '../../../com/atproto/label/defs.defs.js'

const $nsid = 'id.sifa.profile.project'

export { $nsid }

/** Record representing a single project. */
type Main = {
  $type: 'id.sifa.profile.project'

  /**
   * Project name.
   */
  name: string

  /**
   * Description of the project, the user's role, and outcomes.
   */
  description?: string

  /**
   * URL of the project (website, repository, demo, etc.).
   */
  url?: l.UriString

  /**
   * Reference to the first-class id.sifa.project.self record, if this personal project entry corresponds to a collaborative project.
   */
  projectRef?: RepoStrongRef.Main

  /**
   * Reference to the associated id.sifa.profile.position record, if applicable.
   */
  position?: RepoStrongRef.Main

  /**
   * Project start date in YYYY-MM or YYYY-MM-DD format.
   */
  startedAt?: string

  /**
   * Project end date in YYYY-MM or YYYY-MM-DD format. Omit if ongoing.
   */
  endedAt?: string

  /**
   * Self-label values for this project record.
   */
  labels?: l.$Typed<LabelDefs.SelfLabels> | l.Unknown$TypedObject

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** Record representing a single project. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    name: l.string({ minLength: 1, maxGraphemes: 256, maxLength: 2560 }),
    description: l.optional(l.string({ maxGraphemes: 5000, maxLength: 50000 })),
    url: l.optional(l.string({ format: 'uri' })),
    projectRef: l.optional(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
    position: l.optional(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
    startedAt: l.optional(l.string()),
    endedAt: l.optional(l.string()),
    labels: l.optional(
      l.typedUnion(
        [l.typedRef<LabelDefs.SelfLabels>((() => LabelDefs.selfLabels) as any)],
        false,
      ),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
