/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";
import * as SifaDefs from "../defs.defs.js";
import * as LabelDefs from "../../../com/atproto/label/defs.defs.js";

const $nsid = "id.sifa.profile.self";

export { $nsid };

/** The user's professional profile summary. */
type Main = {
  $type: "id.sifa.profile.self";

  /**
   * Professional headline (e.g., 'Senior Engineer at Acme Corp'). Distinct from Bluesky's displayName.
   */
  headline?: string;

  /**
   * Professional summary or about section. Longer-form than Bluesky's description field.
   */
  about?: string;

  /**
   * Primary professional industry.
   */
  industry?: string;

  /**
   * Professional location (city, region, country).
   */
  location?: SifaDefs.LocationAddress;

  /**
   * Types of opportunities the user is open to. Empty array or omitted means not actively seeking.
   */
  openTo?: (
    | "id.sifa.defs#fullTimeRoles"
    | "id.sifa.defs#partTimeRoles"
    | "id.sifa.defs#contractRoles"
    | "id.sifa.defs#boardPositions"
    | "id.sifa.defs#mentoringOthers"
    | "id.sifa.defs#beingMentored"
    | "id.sifa.defs#collaborations"
    | l.UnknownString
  )[];

  /**
   * Preferred workplace arrangements. Orthogonal to openTo. Empty array or omitted means no preference.
   */
  preferredWorkplace?: (
    | "id.sifa.defs#onSite"
    | "id.sifa.defs#remote"
    | "id.sifa.defs#hybrid"
    | l.UnknownString
  )[];

  /**
   * BCP 47 language tags indicating the user's primary professional languages.
   */
  langs?: l.LanguageString[];

  /**
   * Self-label values for the professional profile.
   */
  labels?: l.$Typed<LabelDefs.SelfLabels> | l.Unknown$TypedObject;

  /**
   * Client-declared timestamp when this profile was originally created.
   */
  createdAt: l.DatetimeString;
};

export type { Main };

/** The user's professional profile summary. */
const main = l.record<"literal:self", Main>(
  "literal:self",
  $nsid,
  l.object({
    headline: l.optional(l.string({ maxGraphemes: 120, maxLength: 1200 })),
    about: l.optional(l.string({ maxGraphemes: 5000, maxLength: 50000 })),
    industry: l.optional(l.string({ maxGraphemes: 100, maxLength: 1000 })),
    location: l.optional(
      l.ref<SifaDefs.LocationAddress>((() => SifaDefs.locationAddress) as any),
    ),
    openTo: l.optional(
      l.array(
        l.string<{
          knownValues: [
            "id.sifa.defs#fullTimeRoles",
            "id.sifa.defs#partTimeRoles",
            "id.sifa.defs#contractRoles",
            "id.sifa.defs#boardPositions",
            "id.sifa.defs#mentoringOthers",
            "id.sifa.defs#beingMentored",
            "id.sifa.defs#collaborations",
          ];
        }>(),
        { maxLength: 10 },
      ),
    ),
    preferredWorkplace: l.optional(
      l.array(
        l.string<{
          knownValues: [
            "id.sifa.defs#onSite",
            "id.sifa.defs#remote",
            "id.sifa.defs#hybrid",
          ];
        }>(),
        { maxLength: 3 },
      ),
    ),
    langs: l.optional(
      l.array(l.string({ format: "language" }), { maxLength: 3 }),
    ),
    labels: l.optional(
      l.typedUnion(
        [l.typedRef<LabelDefs.SelfLabels>((() => LabelDefs.selfLabels) as any)],
        false,
      ),
    ),
    createdAt: l.string({ format: "datetime" }),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
