/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from "@atproto/lex";

const $nsid = "id.sifa.profile.skill";

export { $nsid };

/** Record representing a single professional skill. */
type Main = {
  $type: "id.sifa.profile.skill";

  /**
   * Skill name (e.g., 'JavaScript', 'Project Management').
   */
  name: string;

  /**
   * Broad skill category for grouping.
   */
  category?:
    | "id.sifa.defs#technical"
    | "id.sifa.defs#business"
    | "id.sifa.defs#creative"
    | "id.sifa.defs#interpersonal"
    | "id.sifa.defs#language"
    | "id.sifa.defs#industry"
    | l.UnknownString;

  /**
   * Client-declared timestamp when this record was originally created.
   */
  createdAt: l.DatetimeString;
};

export type { Main };

/** Record representing a single professional skill. */
const main = l.record<"tid", Main>(
  "tid",
  $nsid,
  l.object({
    name: l.string({ minLength: 1, maxGraphemes: 64, maxLength: 640 }),
    category: l.optional(
      l.string<{
        knownValues: [
          "id.sifa.defs#technical",
          "id.sifa.defs#business",
          "id.sifa.defs#creative",
          "id.sifa.defs#interpersonal",
          "id.sifa.defs#language",
          "id.sifa.defs#industry",
        ];
      }>(),
    ),
    createdAt: l.string({ format: "datetime" }),
  }),
);

export { main };

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type;
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main);
